### ISSUE TITLE
Random Segfaults

### ISSUE THREAD

**Issue by mhutter** [tnozicka/openshift-acme#62]
At the moment, our acme-controller pod is in a crash loop due to:
```E0328 15:01:49.812890       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:505
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:388
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/acme/client/client.go:130
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:573
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:742
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:749
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:770
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe9796d]

goroutine 103 [running]:
github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0xfc9c80, 0x18e9260)
    /usr/local/go/src/runtime/panic.go:505 +0x229
github.com/tnozicka/openshift-acme/pkg/acme/client.GetAuthorizationErrors(0xc4239eccb0, 0x7, 0x1103a77)
    /opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/acme/client/client.go:130 +0xed
github.com/tnozicka/openshift-acme/pkg/controllers/route.(*RouteController).handle(0xc4200e6000, 0xc421d0f680, 0x25, 0x0, 0x0)
    /opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:573 +0x25ff
github.com/tnozicka/openshift-acme/pkg/controllers/route.(*RouteController).processNextItem(0xc4200e6000, 0xc4200c6600)
    /opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:742 +0xde
github.com/tnozicka/openshift-acme/pkg/controllers/route.(*RouteController).runWorker(0xc4200e6000)
    /opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:749 +0x2b
github.com/tnozicka/openshift-acme/pkg/controllers/route.(*RouteController).(github.com/tnozicka/openshift-acme/pkg/controllers/route.runWorker)-fm()
    /opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:770 +0x2a
github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc421d53000)
    /opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc421d53000, 0x3b9aca00, 0x0, 0x1, 0xc42056e240)
    /opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc421d53000, 0x3b9aca00, 0xc42056e240)
    /opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/tnozicka/openshift-acme/pkg/controllers/route.(*RouteController).Run
    /opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:770 +0x1b3
```

I am unsure which route exactly triggers this error, we have 469 routes on our Cluster :-( I try to narrow down which route causes the issue ASAP.

Any Idea during what step the segfault actually happens?

**Comment by mhutter** [comment]
Did some more debugging, I think this happens when a route cannot be verified because of invalid DNS records

**Comment by tnozicka** [comment]
I am looking into this, although I have just noticed it by change since I don't get email notification until I am mentioned or participating in that thread - a tip for next time

**Comment by tnozicka** [comment]
PR ref https://github.com/tnozicka/openshift-acme/pull/63

**Comment by mhutter** [comment]
Wow, I felt bad because the Issue had so little information at first, but that was really fast! 👍 

Thanks for the heads up re: notifications.
